# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nU91KoFEC8_VlbCaJ-9vdEPa-SK5EbB2
"""

import pandas as pd

df1 = pd.read_csv("spam_cleaned.csv")
df2 = pd.read_csv("SMSSpamCollection.csv", sep='\t', names=["label", "text"])

print(df1.columns)
print(df1.head())

df1 = df1.loc[:, ~df1.columns.str.contains('^Unnamed')]

print(df1.columns)
print(df1.head())

print(df2.columns)
print(df2.head())

df = pd.concat([df1, df2], ignore_index=True)

print(df.shape)

print(df.columns)

print(df.duplicated().sum())

df = df.drop_duplicates()

print(df.duplicated().sum())

print(df.isnull().sum())

df['label_final'] = df['v1'].combine_first(df['label'])
df['text_final'] = df['v2'].combine_first(df['text'])

df = df[['label_final', 'text_final']]
df.columns = ['label', 'text']

print(df.head())
print(df.isnull().sum())

print(df.head())

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

df.head()

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['text'] = df['text'].apply(clean_text)

print(df['text'].head(10))
print(df['text'].str.len().describe())

df = df[df['text'].str.strip() != '']

print(df.shape)
print(df['text'].head())
print(df['text'].str.len().describe())

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)
ngram_range = (1, 2)

X = tfidf.fit_transform(df['text']).toarray()
y = df['label']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

import joblib

joblib.dump(model, "spam_model.pkl")

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Simulate a request object for testing in a standalone notebook cell
class MockRequest:
    def __init__(self, json_data):
        self._json_data = json_data

    @property
    def json(self):
        return self._json_data

# Create a mock request instance with sample data
request = MockRequest({"message": "This is a simulated message from the notebook!"})

data = request.json
print("Full Request:", data)
print("Message Value:", data.get("message"))

msg = ["URGENT you won free iphone click now"]

msg_vec = tfidf.transform(msg)
print(model.predict(msg_vec))

tests = [
    "free money win now",
    "hello how are you",
    "claim your prize urgently",
    "let's meet tomorrow"
]

for t in tests:
    print(t, "→", model.predict(tfidf.transform([t])))

!pip install fastapi uvicorn pyngrok nest_asyncio

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class RequestModel(BaseModel):
    message: str

@app.post("/predict")
def predict(req: RequestModel):

    text = req.message.lower()


    if "spam" in text:
        result = "spam"
    else:
        result = "not spam"

    return {"result": result}

from fastapi.middleware.cors import CORSMiddleware

origins = [
    "*",  # أو حدد localhost بس لو عايز أمان أكتر
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run():
    uvicorn.run(app, host="0.0.0.0", port=8005)

thread = threading.Thread(target=run)
thread.start()

from pyngrok import ngrok

ngrok.set_auth_token("3CKBunHu0X76kWGfxFRcSo6Prwr_44Ggo2DSsxwr9sEpLeujd")

ngrok.kill()

public_url = ngrok.connect(8000)

print(public_url.public_url)

public_url = ngrok.connect(8000)
print(public_url)

import nest_asyncio
import uvicorn

nest_asyncio.apply()

config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)

await server.serve()

with open("main.py", "w") as f:
    f.write("""
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message": "API is working"}

@app.post("/predict")
def predict(data: dict):
    return {"result": "ok"}
""")

